
// import { AcUnit } from "@material-ui/icons"
import Navbar from "../components/navbar/Navbar"
import "./home.scss"

const home = () => {
  return (
    <div className='home'>
      <Navbar/>
      <img width="100%" src="https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.5N2CFu7DaXUIhDf5EpdM6wHaEJ%26pid%3DApi&f=1&ipt=72ac7a72145334d511894aa079c6bd4de91ac6ed3ade2eaa9c3f5f4c56d3f077&ipo=images" alt="" />
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Quisquam deserunt officia facilis sint possimus temporibus, assumenda dolorum alias vel. Saepe maxime tempore provident nisi, recusandae earum repellendus id facilis eligendi?
    </div>
  )
}

export default home